version: 2

project_name: vint

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: vint-build
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - android
    goarch:
      - amd64
      - 386
      - arm64
      - arm
    ldflags:
      - "-s -w"
    ignore:
      - goos: android
        goarch: 386
    binary: vint
    main: ./main.go 

archives:
  - format: tar.gz
    name_template: >-
      vint_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md 
    replacements:
      darwin: macOS 

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - maintainer: "Tachera Sasi"
    homepage: "https://vintlang.ekilie.com"
    description: "Vint is a programming language built from the ground up"
    formats:
      - deb
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    license: MIT 

release:
  github:
    owner: ekilie
    name: vint
  draft: false
  prerelease: false
  tag_name: "{{ .Version }}"
  name_template: "{{ .ProjectName }} {{ .Version }}"
  changelog:
    use: true

env:
  - GITHUB_TOKEN 
