//   AUTO-GENERATED FILE - DO NOT EDIT MANUALLY - By Tachera Sasi
// This file is automatically generated at build time by scripts/build-docs.js
// To modify types, edit the script instead - your changes will be overwritten
// Generated at: 2025-09-26T14:19:28.189Z

export interface DocItem {
  title: string;
  href: string;
  description: string;
  filename: string;
}

export interface CategorizedDocs {
  [category: string]: DocItem[];
}

export interface DocsRegistry {
  items: DocItem[];
  categorized: CategorizedDocs;
  generatedAt: string;
}
