# .goreleaser.yml
release:
    github:
      owner: tacheraSasi
      name: vint-lang
  build:
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    main: ./main.go
    ldflags:
      - -s -w
  